version: '3'

services:
  runner:
    image: austinmsn/tomcat-runner:latest
    container_name: tomcat-runner
    ports:
      - 8080:8080
      - 8009:8009
    volumes:
      - ./data/logs:/usr/local/tomcat/logs
      - ./data/conf:/usr/local/tomcat/conf
      - ./data/lib:/usr/local/tomcat/lib
      - ./data/webapps:/usr/local/tomcat/webapps
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always