version: '3'

services:
  runner:
    image: gitlab/gitlab-runner:latest
    container_name: node-runner
    volumes:
      - ./node-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always